### ISSUE TITLE
'Comment' Attribute has no object text issue

### ISSUE THREAD

**Issue by guihadlich** [beaubellamy/TennisStatistics#2]
I'm coming up with the following issue - any idea why that would be?

`Success:  https://www.atpworldtour.com/en/rankings/singles
Success:  https://www.atpworldtour.com/en/rankings/singles?rankDate=2020-03-16&countryCode=all&rankRange=1-500
Success:  https://www.atpworldtour.com/en/players/novak-djokovic/d643/player-activity?year=all&matchType=Singles
Traceback (most recent call last):
  File "/Users/Guilherme/PycharmProjects/untitled1/itf_scraper.py", line 977, in <module>
    write_Player_Activity(player, url)
  File "/Users/Guilherme/PycharmProjects/untitled1/itf_scraper.py", line 484, in write_Player_Activity
    values.append(row.contents[index].text.split())
  File "/Users/Guilherme/anaconda3/envs/tensor2/lib/python3.6/site-packages/bs4/element.py", line 871, in __getattr__
    self.__class__.__name__, attr))
AttributeError: 'Comment' object has no attribute 'text'

Process finished with exit code 1`

**Comment by beaubellamy** [comment]
I ran the code again, and I get the same error.
Its looking at the first table for Novak's yearly results, and finding a string instead of a text attribute.

If you debug the code, you will see that there seems to be a hidden column in the table. This seems to be consistent for all results tables. I'm not sure why they would do this, but I've pushed a fix that you should be able to pull
